CREATE DATABASE php_mysql_crud;

use ;

CREATE TABLE task(
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  Placa VARCHAR(255) NOT NULL,
  Tipo_vehiculo TEXT,
  Hora_Entrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  Hora_Salida TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE task;
